import type { Metadata } from 'next'
import { Raleway, Bowlby_One_SC } from 'next/font/google';
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from"@/src/layout/partials/Header";
import '@/src/styles/main.scss'

const bowlbySC = Bowlby_One_SC({
weight: '400',
display: 'swap',
subsets: ['latin'],
variable: '--font-bowlbySC',
  });

  const raleway = Raleway({
  subsets: ['latin'],
display: 'swap',
 variable: '--font-raleway',	
  });

export const metadata: Metadata = {
  title: '8zense.com',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${bowlbySC.variable} ${raleway.variable} font-sans`}
    >
      <body className={raleway.className}>
        <Header/>
        <div className="bg-gradient-to-b from-neutral-800 to-stone-400 flex flex-col items-center justify-center mx-auto w-[96vw]">
        {children}
        </div>
        </body>
        
    </html>
    </ClerkProvider>
  )
}
